using System.Text;

namespace SRF.Knx.Config;

/// <summary>
/// Generates the content of <c>KnxValues.generated.cs</c> — a <c>partial class KnxValues</c>
/// with one <c>ValueBase&lt;T&gt;</c> property per KNX group address — from a
/// <see cref="HomeCompanionAutoGenEntry"/> mapping.
/// </summary>
/// <remarks>
/// Invoke via <c>srf-network-cli kc --home-companion-code-gen</c>. The output path is
/// configured via <see cref="KnxConfiguration.HomeCompanionCodeGenFile"/>.
/// </remarks>
public static class KnxValuesCodeGenerator
{
    /// <summary>
    /// Generates the full content of <c>KnxValues.generated.cs</c>.
    /// </summary>
    /// <param name="entries">
    /// Mapping of KNX group address strings (e.g. <c>"1/2/3"</c>) to their auto-gen entries.
    /// Produced by <see cref="IKnxConfigFactory.GenerateHomeCompanionAutoGen"/>.
    /// </param>
    /// <returns>Full C# source text ready to be written to disk.</returns>
    public static string Generate(Dictionary<string, HomeCompanionAutoGenEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by srf-network-cli kc --home-companion-code-gen");
        sb.AppendLine("// Do not edit manually. Regenerate when KNX group address configuration changes.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using HomeCompanion.Base.Values;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine();
        sb.AppendLine("namespace HomeCompanion.Integrations.Knx;");
        sb.AppendLine();
        sb.AppendLine("partial class KnxValues");
        sb.AppendLine("{");

        var usedNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var kvp in entries)
        {
            var address = kvp.Key;
            var entry = kvp.Value;
            var csType = GetCSharpType(entry.Dpt);
            var propName = MakeUnique(entry.PropertyName, usedNames);
            var summaryText = !string.IsNullOrWhiteSpace(entry.Label)
                ? $"{EscapeXmlComment(entry.Label)} (<c>{address}</c>)"
                : $"{EscapeXmlComment(entry.PropertyName)} (<c>{address}</c>)";

            sb.AppendLine($"    /// <summary>{summaryText}</summary>");
            if (!string.IsNullOrWhiteSpace(entry.Description))
                sb.AppendLine($"    /// <remarks>{EscapeXmlComment(entry.Description!)}</remarks>");
            sb.AppendLine($"    public ValueBase<{csType}> {propName} {{ get; }} = new(loggerFactory.CreateLogger<ValueBase<{csType}>>())");
            sb.AppendLine("    {");
            sb.AppendLine($"       Name = \"{propName}\",");
            sb.AppendLine($"       Label = {(string.IsNullOrWhiteSpace(entry.Label) ? "null" : $"\"{entry.Label}\"")},");
            sb.AppendLine("        BusMappings = new Dictionary<object, IValueBusEndpointMapping>");
            sb.AppendLine("        {");
            sb.AppendLine($"            [KnxBusEndpointMapping.BusId] = new KnxBusEndpointMapping(\"{address}\")");
            sb.AppendLine("        }");
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // -------------------------------------------------------------------------
    // DPT → C# type mapping  (stable per KNX specification)
    // -------------------------------------------------------------------------

    /// <summary>
    /// Maps a DPT main number to the C# value type used in <c>ValueBase&lt;T&gt;</c>.
    /// DPT strings have the form <c>"DPST-X-Y"</c> or <c>"DPT-X"</c>.
    /// </summary>
    //TODO: As we're in a Cli context, we could use full SRF.Knx functionality to resolve DPTs, including custom ones as required and ensure coverage of the actual ETS export.
    private static string GetCSharpType(string? dpt)
    {
        if (string.IsNullOrEmpty(dpt))
            return "byte[]";

        var parts = dpt!.Split('-');
        if (parts.Length < 2 || !int.TryParse(parts[1], out var main))
            return "byte[]";

        return main switch
        {
            1 => "bool",      // 1-bit switch/boolean
            2 => "byte",      // 2-bit controlled
            3 => "byte",      // 4-bit dimming
            4 => "char",      // 1-byte character
            5 => "byte",      // 1-byte unsigned (0–100 %, angles, …)
            6 => "sbyte",     // 1-byte signed
            7 => "ushort",    // 2-byte unsigned
            8 => "short",     // 2-byte signed
            9 => "float",     // KNX 2-byte float (EIS 5)
            10 => "byte[]",   // Time of day (complex)
            11 => "byte[]",   // Date (complex)
            12 => "uint",     // 4-byte unsigned
            13 => "int",      // 4-byte signed
            14 => "float",    // IEEE 754 4-byte float
            16 => "string",   // ISO 8859-1 character string
            17 => "byte",     // Scene number
            18 => "byte",     // Scene control
            19 => "byte[]",   // Date & time (complex)
            _ => main >= 20 && main <= 29 ? "byte" : "byte[]"
        };
    }

    private static string MakeUnique(string name, HashSet<string> used)
    {
        if (used.Add(name))
            return name;
        for (var i = 2; ; i++)
        {
            var candidate = $"{name}_{i}";
            if (used.Add(candidate))
                return candidate;
        }
    }

    private static string EscapeXmlComment(string text) =>
        text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\n", "<br/>")
            .Replace("\r", "");
}
