<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="./Resources/knx_master.xml" Link="knx_master.xml" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="./Resources/UnitSystemConfig.json" Link="UnitSystemConfig.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="OpenHab/Generate/base/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\HomeCompanion.Knx.Shared\HomeCompanion.Knx.Shared.csproj" />
    <ProjectReference Include="..\SRF.Knx.Core\SRF.Knx.Core.csproj" />
  </ItemGroup>
</Project>
